### ISSUE TITLE
Can't get any of the mask controls to bind to a value.

### ISSUE THREAD

**Issue by jackmatt2** [text-mask/ember-text-mask-addons#25]
I'm trying to bind the input value to `control.answer` but for some reason this is not working (control.answer is never updated).

```
{{number-mask control.answer prefix='' allowDecimal=true decimalLimit=2 allowNegative=false class="form-control" }}
```

Am I doing something wrong?

**Comment by lozjackson** [comment]
you need to bind to the value attribute of the input element. ie `value=control.answer`

```
{{number-mask value=control.answer prefix='' allowDecimal=true decimalLimit=2 allowNegative=false class="form-control" }}
```

Hope that helps

**Comment by jackmatt2** [comment]
Ah, thanks.  I am used to using ember-one-way-controls which do it as above.
